# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SBFResImg(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, file_body: str=None, file_name: str=None, file_type: str=None):  # noqa: E501
        """SBFResImg - a model defined in Swagger

        :param file_body: The file_body of this SBFResImg.  # noqa: E501
        :type file_body: str
        :param file_name: The file_name of this SBFResImg.  # noqa: E501
        :type file_name: str
        :param file_type: The file_type of this SBFResImg.  # noqa: E501
        :type file_type: str
        """
        self.swagger_types = {
            'file_body': str,
            'file_name': str,
            'file_type': str
        }

        self.attribute_map = {
            'file_body': 'fileBody',
            'file_name': 'fileName',
            'file_type': 'fileType'
        }

        self._file_body = file_body
        self._file_name = file_name
        self._file_type = file_type

    @classmethod
    def from_dict(cls, dikt) -> 'SBFResImg':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SBFResImg of this SBFResImg.  # noqa: E501
        :rtype: SBFResImg
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file_body(self) -> str:
        """Gets the file_body of this SBFResImg.


        :return: The file_body of this SBFResImg.
        :rtype: str
        """
        return self._file_body

    @file_body.setter
    def file_body(self, file_body: str):
        """Sets the file_body of this SBFResImg.


        :param file_body: The file_body of this SBFResImg.
        :type file_body: str
        """

        self._file_body = file_body

    @property
    def file_name(self) -> str:
        """Gets the file_name of this SBFResImg.


        :return: The file_name of this SBFResImg.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name: str):
        """Sets the file_name of this SBFResImg.


        :param file_name: The file_name of this SBFResImg.
        :type file_name: str
        """

        self._file_name = file_name

    @property
    def file_type(self) -> str:
        """Gets the file_type of this SBFResImg.


        :return: The file_type of this SBFResImg.
        :rtype: str
        """
        return self._file_type

    @file_type.setter
    def file_type(self, file_type: str):
        """Sets the file_type of this SBFResImg.


        :param file_type: The file_type of this SBFResImg.
        :type file_type: str
        """

        self._file_type = file_type
