---
swagger: "2.0"
info:
  description: "API for the parser microservice"
  version: "1.1.0"
  title: "Swagger Parser Microservice"
host: "localhost:8081"
basePath: "/api"
schemes:
  - "http"
paths:
  /pht:
    post:
      description: "Queries the database for information."
      operationId: "pht_bot"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "json_input"
          description: "User ID"
          required: true
          schema:
            $ref: "#/definitions/SBF"
      responses:
        "200":
          description: "OK. User Information."
          schema:
            $ref: "#/definitions/SBFRes"
        "500":
          description: "Internal Server error."
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  SBF:
    type: "object"
    required:
      - "botName"
      - "channel"
      - "email"
      - "entities"
      - "intent"
      - "time"
      - "user"
    properties:
      mgs:
        type: "string"
      botName:
        type: "string"
      channel:
        type: "string"
      intent:
        type: "string"
      entities:
        type: "object"
        properties: {}
      email:
        type: "string"
      user:
        type: "string"
      time:
        type: "string"
    example:
      entities: "entities"
      botName: "botName"
      mgs: "mgs"
      channel: "channel"
      time: "time"
      intent: "intent"
      user: "user"
      email: "email"
  SBFRes:
    type: "object"
    properties:
      text:
        type: "string"
      closeContext:
        type: "string"
    example:
      text: "text"
      closeContext: "closeContext"
  SBFResImg:
    type: "object"
    properties:
      fileBody:
        type: "string"
      fileName:
        type: "string"
      fileType:
        type: "string"
