#Examples to be used with the VS Code extension REST Client

POST http://localhost:8081/api/user HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "",
    "entities": {"userID": {"value": "u1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST https://milki-psy.dbis.rwth-aachen.de/api/user HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "",
    "entities": {"userID": {"value": "u4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
### debug
POST http://localhost:8081/api/train/request HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_title",
    "entities": {"stations": {"value": "Private-Weber2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/request HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_title",
    "entities": {"stations": {"value": "Private_TEST"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_owner",
    "entities": {"stationID": {"value": "station1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_owner",
    "entities": {"stationID": {"value": "station_aachen"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_responsible",
    "entities": {"stationID": {"value": "stationMinimal"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_responsible",
    "entities": {"stationID": {"value": "station_cologne"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_cert",
    "entities": {"stationID": {"value": "station2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_cert",
    "entities": {"stationID": {"value": "station_leipzig"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_title",
    "entities": {"stationID": {"value": "station3"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_title",
    "entities": {"stationID": {"value": "station_mittweida"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "comp_env",
    "entities": {"stationID": {"value": "station1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "comp_env",
    "entities": {"stationID": {"value": "station_leipzig_imise"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_dataset",
    "entities": {"stationID": {"value": "station4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_dataset",
    "entities": {"stationID": {"value": "station_aachen"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_info",
    "entities": {"stationID": {"value": "station5"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_info",
    "entities": {"stationID": {"value": "station_cologne"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "upcomming_trains",
    "entities": {"stationID": {"value": "stationMinimal"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "upcomming_trains",
    "entities": {"stationID": {"value": "station_cologne"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "current_at_station",
    "entities": {"stationID": {"value": "station3"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "current_at_station",
    "entities": {"stationID": {"value": "station_leipzig"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_error",
    "entities": {"stationID": {"value": "station6"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_error",
    "entities": {"stationID": {"value": "station_leipzig_imise"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_log",
    "entities": {"stationID": {"value": "station3"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_log",
    "entities": {"stationID": {"value": "station_mittweida"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_rejections",
    "entities": {"stationID": {"value": "station1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/station/execution HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "station_rejections",
    "entities": {"stationID": {"value": "station_cologne"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_info",
    "entities": {"trainID": {"value": "train1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_info",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_model",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/information HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_model",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "planned_route",
    "entities": {"trainID": {"value": "train3"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "planned_route",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_error",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_error",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_log",
    "entities": {"trainID": {"value": "train1"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_log",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_rejection",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "train_rejection",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "current_station",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/train/runtime HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "current_station",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/all HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "all_stations",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/all HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "all_trains",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/help HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "help",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/help HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "help",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"trainID": {"value": "train2"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"trainID": {"value": "train4"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"trainID": {"value": "train2"}, "amount": {"value": "average"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"trainID": {"value": "train4"}, "amount": {"value": "average"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST http://localhost:8081/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"stationID": {"value": "station5"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}

###
POST https://milki-psy.dbis.rwth-aachen.de/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"stationID": {"value": "station_goettingen"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST https://milki-psy.dbis.rwth-aachen.de/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"stationID": {"value": "station_aachen"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}
###
POST https://milki-psy.dbis.rwth-aachen.de/api/performance HTTP/1.1
content-type: application/json

{
    "msg":"TestMessage",
    "botName": "TestBot",
    "channel": "TestChannel",
    "intent": "get_performance",
    "entities": {"stationID": {"value": "station_cologne"}} ,
    "email": "Test@email.com",
    "user": "TestUser",
    "time": "1644224769.807741"
}